#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================


source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_app_setting_set_default --key=php_upload_max_filesize --value=10M
ynh_app_setting_set_default --key=php_post_max_size --value=10M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".env"

pushd $install_dir
	ynh_script_progression "Refreshing dependencies...\n"
	#REMOVEME? ynh_composer_install
	ynh_composer_exec install --no-dev

	ynh_script_progression "Updating database...\n"
	php$php_version artisan migrate --force

	ynh_script_progression "Clearing cache...\n"
	php$php_version artisan view:cache
	php$php_version artisan config:cache
	php$php_version artisan event:cache
	php$php_version artisan route:clear
popd

#=================================================
# UPDATE A CONFIG FILE
#=================================================
#ynh_script_progression "Updating $app's configuration files..."

#ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
